### ISSUE TITLE
JedisUtil类的改进

### ISSUE THREAD

**Issue by funyule** [xuxueli/xxl-sso#12]
为了充分利用Redis自己的逻辑分库，可以改进JedisUtil类，将SSO中心用于登陆的信息存在Redis指定的库中，用以区分其他库里存储其他的内容信息,还有大多数的redis可能会设置密码
修改代码的地方：
``
>String redisAddress = "http://username:password@ip:port/dbIndex";
>JedisShardInfo jedisShardInfo = new JedisShardInfo(redisAddress);
``

**Comment by xuxueli** [comment]
赞！期待PR啊
