### ISSUE TITLE
文档拼写错误

### ISSUE THREAD

**Issue by longwusha** [xuxueli/xxl-sso#21]
原文：
4.7 基于Token，相关感念

应为：
4.7 基于Token，相关概念

**Comment by xuxueli** [comment]
赞！ 欢迎一起参与进来啊！可以提交PR修复这个问题！

**Comment by longwusha** [comment]
@xuxueli 

已提交PR，请及时检视合入，谢谢！

**Comment by xuxueli** [comment]
赞，已合并！
