### ISSUE TITLE
【疑问】Client使用或配置redis

### ISSUE THREAD

**Issue by tianzhonghai** [xuxueli/xxl-sso#23]
你好。如题，为什么客户端还要配置redis呢？我认为这应该是server端实现的细节。

**Comment by limpidck** [comment]
不同的设计方式吧，整个项目中，client端的redis现仅用于SSO_USER的获取并在请求中传递，个人觉得实现上有三种思路可考虑（个人看源码的见解，如有不对，请指正，谢谢）：
1、server和client用相同的介质(例如现有的redis)存储用户及权限信息，这种情况的话，server端后续不仅做用户登录信息校验，同时做各系统资源权限配置
2、server和client用相同的介质(例如现有的redis)仅存储用户信息，这种情况，权限交由各client端去配置实现
3、server和client约定并配置登录成功后生成的sessionId和用户标识（如手机号）的加解密方式，这样server端就仅做登录校验并返回生成的用户标识sessionId信息，其它的就完全交由client端去实现了，这样client和server就没有什么组件耦合关系

**Comment by limpidck** [comment]
> 你好。如题，为什么客户端还要配置redis呢？我认为这应该是server端实现的细节。
不同的设计方式吧，整个项目中，client端的redis现仅用于SSO_USER的获取并在请求中传递，个人觉得实现上有三种思路可考虑（个人看源码的见解，如有不对，请指正，谢谢）：
1、server和client用相同的介质(例如现有的redis)存储用户及权限信息，这种情况的话，server端后续不仅做用户登录信息校验，同时做各系统资源权限配置
2、server和client用相同的介质(例如现有的redis)仅存储用户信息，这种情况，权限交由各client端去配置实现
3、server和client约定并配置登录成功后生成的sessionId和用户标识（如手机号）的加解密方式，这样server端就仅做登录校验并返回生成的用户标识sessionId信息，其它的就完全交由client端去实现了，这样client和server就没有什么组件耦合关系

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-sso/issues/20
