### ISSUE TITLE
xxl-sso-sample-springboot  包路径有问题

### ISSUE THREAD

**Issue by fasoal** [xuxueli/xxl-sso#3]
![x 173 7etys1_bh61t 2g3](https://user-images.githubusercontent.com/14243815/38477168-e185dda2-3be3-11e8-80c2-b34f98cc44e2.png)

**Comment by xuxueli** [comment]
你好，感谢反馈啊！
已经修复路径问题，稍后将随新特性代码一并托送master分支。
