### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by Yyy1231456** [xuxueli/xxl-sso#30]
感觉客户端项目最好还是不要连接sso-server的redis，如果能吧票据的校验换成http请求来请求sso-server而不是直接通过redis来查询会不会更好呢？这样客户端和sso-server的耦合度也低了很多

**Comment by gyf6067** [comment]
这样每次Request请求都会多一次HTTP，性能会减少。。。

**Comment by iwin4aids** [comment]
> 这样每次Request请求都会多一次HTTP，性能会减少。。。

哪里需要每次请求多一次http，只需要第一次去验证拿到用户相关信息，后面本地session已经创建了就不需要validate了

**Comment by gyf6067** [comment]
> 
> 
> > 这样每次Request请求都会多一次HTTP，性能会减少。。。
> 
> 哪里需要每次请求多一次http，只需要第一次去验证拿到用户相关信息，后面本地session已经创建了就不需要validate了

xxl-sso架构貌似是摒弃了本地session，把本地session转移到redis，所有请求都需先到redis校验是否失效。

**Comment by MingH-Chen** [comment]
个人感觉。sso-server 存储的会话信息应该对于应用是透明的，最好以接口的方式提供出去，每次校验。当然性能上可能会有一定的影响。如果本地缓存session信息的话，那就存在不一致的情况。这里面可以考虑最终一致，不过最终还是结合业务考虑

**Comment by xuxueli** [comment]
合并至：https://github.com/xuxueli/xxl-sso/issues/20
