### ISSUE TITLE
支持多域名的单点登录吗

### ISSUE THREAD

**Issue by KoalaInTree** [xuxueli/xxl-sso#38]

**Comment by xuxueli** [comment]
你好，支持跨域的。

**Comment by wolfyg** [comment]
雪里大佬回复万分荣幸！！！
雪里大哥支持的



---原始邮件---
发件人: "许雪里"<notifications@github.com&gt;
发送时间: 2019年12月13日(周五) 晚上7:24
收件人: "xuxueli/xxl-sso"<xxl-sso@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [xuxueli/xxl-sso] 支持多域名的单点登录吗 (#38)



你好，支持跨域的。

**Comment by KoalaInTree** [comment]
感谢~~~
