### ISSUE TITLE
能在介绍里说明一下和cas saml等的区别和优缺点吗？不知道该怎么选型进行比较。

### ISSUE THREAD

**Issue by choothui** [xuxueli/xxl-sso#40]

**Comment by xuxueli** [comment]
XXL-SSO解决的是单点登录问题。，对身份认证的具体方法不做要求。
saml、或者Oauth、openID解决的是身份认证授权的问题。

是两个领域。

**Comment by JPCui** [comment]
> XXL-SSO解决的是单点登录问题。，对身份认证的具体方法不做要求。
> saml、或者Oauth、openID解决的是身份认证授权的问题。
> 
> 是两个领域。

CAS也能做单点登录，xxl-sso和CAS对比有什么优缺点，现在很多开源SDK都支持CAS，为什么要用你这个？优缺点怎么体现，建议有个说明，不能一味的造轮子
