### ISSUE TITLE
http://47.105.151.82:2200/sso

### ISSUE THREAD

**Issue by wolfyg** [xuxueli/xxl-sso#47]
admin/111111

**Comment by wolfyg** [comment]
https://blog.csdn.net/BeiShangBuZaiLai/article/details/102930078

**Comment by xuxueli** [comment]
地址失效。

**Comment by wolfyg** [comment]
地址我换了您可以看看
http://116.196.102.142:2200/sso

我换了新服务器



---Original---

**Comment by wolfyg** [comment]
我更新了地址



---Original---

**Comment by 852675742** [comment]
能否提供下源码
