### ISSUE TITLE
增加框架的通用性

### ISSUE THREAD

**Issue by shyboy0358** [xuxueli/xxl-sso#5]
增加框架的通用性，例如：sso-client.jar  sso-server.war，达到真正的开箱及用

**Comment by xuxueli** [comment]
你好，感谢反馈！
Client端依赖已经推送到maven中央仓库，只需要配置pom依赖即可引用，非常方便。
SSO Server只需要简单mvn编辑即可，后续将会提供docker镜像，进一步方便接入使用。
