### ISSUE TITLE
前后端分离的项目怎么集成呢？

### ISSUE THREAD

**Issue by vainly** [xuxueli/xxl-sso#56]
如体，前端项目使用的vue/react ，后端ssm，这样的项目怎么集成sso呢？

**Comment by wolfyg** [comment]
看看我的
用户管理后台
http://116.196.102.142:2200/sso
admin/111111
门户地址
http://116.196.102.142:8089/uac
系统所有初始用户密码均为123456
test/123456(该用户使用了自定义门户)
test1/123456(该用户使用的默认门户)


---原始邮件---
发件人: "sticver"<notifications@github.com&gt;
发送时间: 2020年9月27日(周日) 晚上7:28
收件人: "xuxueli/xxl-sso"<xxl-sso@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [xuxueli/xxl-sso] 前后端分离的项目怎么集成呢？ (#56)




 
如体，前端项目使用的vue/react ，后端ssm，这样的项目怎么集成sso呢？

**Comment by dangerousSun** [comment]
@wolfyg  有源码吗哥

**Comment by wolfyg** [comment]
这不是废话么肯定有哇




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuxueli/xxl-sso"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月9日(星期五) 下午4:10
收件人:&nbsp;"xuxueli/xxl-sso"<xxl-sso@noreply.github.com&gt;;
抄送:&nbsp;"ggboy "<597205393@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xuxueli/xxl-sso] 前后端分离的项目怎么集成呢？ (#56)





 
@wolfyg  有源码吗哥

**Comment by dangerousSun** [comment]
@wolfyg 跪求

**Comment by cxlings** [comment]
这个是前后端分离的吗，能分享出来吗？

**Comment by qiuhui1987** [comment]
@wolfyg 方便分享一下吗

**Comment by vainly** [comment]
已经完成

**Comment by Gxmg** [comment]
求分享源码

**Comment by stick777** [comment]
> 这个是前后端分离的吗，能分享出来吗？
同求
