### ISSUE TITLE
需要考虑ajax请求的重定向兼容问题

### ISSUE THREAD

**Issue by shyboy0358** [xuxueli/xxl-sso#6]
需要考虑ajax请求的重定向兼容问题

**Comment by xuxueli** [comment]
你好，感谢反馈！
这条建议非常有意义，已经加入到TODO排期，也欢迎PR一起完善啊。

（未登录情况下，页面请求 redirect，JSON请求应该返回 sso 登陆失败的错误提示）

**Comment by xuxueli** [comment]
你好，该建议已经实现并推送master，可以参考体验。
